Prefixo no username quando o e-mail começa com dígito
uspdev/web-ldap-admin pull request #149
Opened 2022-10-06 17:32 UTC by alecostaweb

Fix #148 

Quando CAMPO_CODPES=employeeNumber e o e-mail começar com dígito, o prefixo PREFIX_USERNAME= é adicionado no início do username.

Exemplo:
 
CAMPO_CODPES=employeeNumber
PREFIX_USERNAME=x

Fulano de Tal, e-mail 777fulano.tal@usp.br, o username será x777fulanotal

2022-10-19 12:21 UTC, thiagogomesverissimo requested changes
@alecostaweb testei sua PR no web-ldap-admin, alguns comentários:

- Resolve o problema apresentado pela Sybele :+1: 
- A alternativa de prefixar o email só quando ele é completamente numérico foi uma boa sacada
- Acho que: a identificação do login ficou "um pouco complicada", pois o usuário deverá digitar o email com diversos restrições: 1) sem caracteres especiais 2) somente até o arroba 3) prefixar quando email é completamente numérico
- Como solução vejo duas alternativas: 1) Prefixar o codpes mesmo e não o email 2) deixar como está, mas mostrar na "minha conta" do web-ldap-admin o que o usuário deve usar como username

2022-10-19 12:31 UTC, alecostaweb commented
- Na verdade não resolve porque a Sybele prefere prefixar o codpes

- A sacada foi sua, eu só segui a dica 👍

- Concordo sobre usar o e-mail, mas o Masaki usa assim na EESC

- Sim, deve-se mostrar ou destacar como deve ser o username 

Acho que precisamos entrar em um consenso de como parametrizar a questão do username a fim de atender o uso das unidades que utilizam o web-ldap-admin

2022-11-16 13:52 UTC, alecostaweb commented
Ajustes ainda por fazer nessa PR:
#150

2024-08-30 13:38 UTC, alecostaweb commented
Fix #148

2024-08-30 13:38 UTC, closed without merging